name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa 3.81.87.146 >> ~/.ssh/known_hosts

    - name: Copy Script to Remote Instance
      run: |
        scp -i ~/.ssh/id_rsa ./script.sh ubuntu@3.81.87.146:/home/ubuntu/

    - name: Execute Deployment Script on Remote Instance & Remove Script from Remote Instance
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@3.81.87.146 "chmod +x /home/ubuntu/script.sh && /home/ubuntu/script.sh"
        ssh -i ~/.ssh/id_rsa ubuntu@3.81.87.146 "rm /home/ubuntu/script.sh"
